### ISSUE TITLE
tiovxmosaic: EOS to be handled separately for sources

### ISSUE THREAD

**Issue by aniket-l** [TexasInstruments/edgeai-gst-plugins#106]
On EOS from one source, all other sources should keep running.

This will exit after 1s
> gst-launch-1.0 videotestsrc pattern=ball ! video/x-raw,format=NV12, width=640, height=360 ! queue ! mosaic.sink_0 videotestsrc pattern=ball num-buffers=30 ! video/x-raw,format=NV12, width=640, height=360 ! queue ! mosaic.sink_1 tiovxmosaic name=mosaic sink_0::startx=0   sink_0::starty=0   sink_0::width=640  sink_0::height=360 sink_1::startx=640 sink_1::starty=0   sink_1::width=640  sink_1::height=360 ! video/x-raw,format=NV12, width=1280, height=720 ! kmssink sync=false driver-name=tidss

When using gst.parse_launch() for the above command string, both the videos freeze after 1s. One of them should keep running.

**Comment by rrcarlosrodriguez** [comment]
@aniket-l this issue should be fixed in the latest v0.4.0 release. Could you please check and close the issue if it is fixed in your test?
