### ISSUE TITLE
Cross-compile issue

### ISSUE THREAD

**Issue by akzare** [TexasInstruments/edgeai-gst-plugins#124]
`commit f9b4bd88dc9a4299f6f02e94ea78472de49d0a9b (HEAD -> main, tag: v0.2.3, origin/main, origin/HEAD)`

I've followed the cross compile instructions, but it fails:
```
a@ubuntu18-04:~/home/edgeai-gst-plugins$ export PSDKR_PATH=/home/ti/ti-processor-sdk-rtos-j721e-evm-08_00_00_12
a@ubuntu18-04:~/home/edgeai-gst-plugins$ crossbuild/environment $PSDKR_PATH > aarch64-none-linux-gnu.ini
a@ubuntu18-04:~/home/edgeai-gst-plugins$ meson build --cross-file aarch64-none-linux-gnu.ini --cross-file crossbuild/crosscompile.ini

ERROR: Malformed value in cross file variable c.
```

**Comment by emmadrigal** [comment]
@akzare I can't reproduce this with the latest release,

Can you check that you have an updated meson version?

**Comment by ravi-rahul** [comment]
This issue is not reproducible
please migrate to latest EdgeAI release

https://www.ti.com/tool/download/PROCESSOR-SDK-LINUX-SK-TDA4VM
