### ISSUE TITLE
tiovxmosaic produces corrupted output when non-tiovx buffers are given as input

### ISSUE THREAD

**Issue by ravi-rahul** [TexasInstruments/edgeai-gst-plugins#185]
Tiovxmosaic is producing green corrupted output when non-tiovx buffers are given as input

Will be sharing the steps to reproduce

**Comment by m-herrera** [comment]
@ravi-rahul Please provide the steps when you get a change, thanks.

**Comment by ravi-rahul** [comment]
Hi @m-herrera 

This is not a plugin issue
it was a bug in the application
