### ISSUE TITLE
tiovxmultiscaler roi doesnot working

### ISSUE THREAD

**Issue by min0628** [TexasInstruments/edgeai-gst-plugins#217]
Hi,

I found that `tiovxmultiscaler` pad template has ROI properties in doc
https://github.com/TexasInstruments/edgeai-gst-plugins/wiki/tiovxmultiscaler

So I try to use ROI properties like this:
```shell
$ gst-launch-1.0 rtspsrc location="rtsp://***/live/main" latency=0 buffer-mode=auto ! rtph264depay ! h264parse ! v4l2h264dec ! tiovxmultiscaler sink::roi-width=700 sink::roi-height=700 sink::roi-startx=300 sink::roi-starty=300 ! queue ! video/x-raw, width=192
0, height=1080 ! kmssink sync=false driver-name=tidss
```
However, the displayed result is no different from the input video.
Even if I modified the EdgeAI App's pipeline, the result was the same.
```shell
rtspsrc location=rtsp://***/live/main latency=0 buffer-mode=auto ! rtph264depay ! h264parse ! v4l2h264dec ! video/x-raw, format=NV12 ! tiovxmultiscaler sink::roi-width=700 sink::roi-height=700 sink::roi-startx=300 sink::roi-starty=300 name=multiscaler_split_00 multiscaler_split_00. ! queue ! video/x-raw, width=1920, height=1080 ! tiovxdlcolorconvert out-pool-size=4 target=1 ! video/x-raw, format=RGB ! appsink drop=true max-buffers=2 name=flow0_sensor0 multiscaler_split_00. ! queue ! video/x-raw, width=512, height=512 ! tiovxdlpreproc target=0 data-type=3 channel-order=0 tensor-format=rgb out-pool-size=4 ! application/x-tensor-tiovx ! appsink drop=true max-buffers=2 name=flow0_pre_proc0
```
I thought that if I set the ROI properties, It would crop the area.

Am I doing something wrong? Or doesn't it support ROI?

Regards,
Lee

**Comment by ravi-rahul** [comment]
Hi Lee,

This is fixed in the develop branch now
in below commit 
https://github.com/TexasInstruments/edgeai-gst-plugins/commit/20c82753d25ed39d9497faebc79e70b2ea27dd5d

Regards
Rahul T R
