### ISSUE TITLE
tiovxcolorconvert: I420 content issue with some resolutions

### ISSUE THREAD

**Issue by emmadrigal** [TexasInstruments/edgeai-gst-plugins#27]
For some of the resolutions the stride calculation appears to be incorrect, resulting in a corrupted frame at the exit, for example:

```
gst-launch-1.0 \
videotestsrc num-buffers=20 ! \
"video/x-raw,format=RGB,width=320,height=240" ! tiovxcolorconvert ! \
"video/x-raw,format=I420" !  filesink location=image.bin
```

**Comment by emmadrigal** [comment]
gst-launch-1.0 \
videotestsrc num-buffers=20 ! \
"video/x-raw,format=RGB,width=1920,height=1080" ! tiovxcolorconvert ! \
"video/x-raw,format=I420" ! filesink location=image.bin

**Comment by emmadrigal** [comment]
This is caused by incorrect handling by kmssink of the buffer width and height which is included as part of the GstVideoMeta in the buffer.

**Comment by ravi-rahul** [comment]
this is fixed now
