### ISSUE TITLE
Output is not correct whenever not tiovx buffers are processed by tiovx plugins

### ISSUE THREAD

**Issue by ravi-rahul** [TexasInstruments/edgeai-gst-plugins#61]
GST_DEBUG=tiovx*:4 gst-launch-1.0 multifilesrc location=/opt/i420/%010u.yuv index=100 loop=true ! video/x-raw, format=I420, width=1280, height=720, framerate=30/1 ! tiovxcolorconvert !  video/x-raw, format=NV12 ! kmssink
 
 output is not correct for this pipeline
 similar behavior whenever non tiovx buffers are processed

**Comment by ravi-rahul** [comment]
the issue can also be reproduced in the application using below steps

1. sync the edge_ai_apps git repo to get the updated video file
2. Modify the config file configs/image_classification.yaml to set the input as video like below
         flows:
             flow0:
                 input: input1 (change input0 to input1)
                 
 3. run the application
      cd apps_python
      ./app_edgeai.py ../configs/image_classification.yaml

**Comment by ravi-rahul** [comment]
first run the demo with camera input
after that if we run demo with file input we can see the traces of camera frame in the output

**Comment by ravi-rahul** [comment]
Hi @emmadrigal 

I tested the application with fix/memory-copy branch
the issue is not coming, getting correct output

**Comment by rrcarlosrodriguez** [comment]
That's great @ravi-rahul ! We will proceed with the merge into develop

Feel free to close this issue whenever you want
