### ISSUE TITLE
Change copy debug level to `GST_PERFORMANCE`

### ISSUE THREAD

**Issue by emmadrigal** [TexasInstruments/edgeai-gst-plugins#72]
In the following debug call: https://github.com/TexasInstruments/edgeai-gst-plugins/blob/develop/gst-libs/gst/tiovx/gsttiovxutils.c#L578

The debug level should be changed to `GST_PERFORMANCE` since that is the gstreamer standard for copy loggging

**Comment by jafet-chaves** [comment]
Fixed in #109
